[project]
name = "repl-nix-spotifymusicdownloader"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "flask>=3.0.3",
    "pydub>=0.25.1",
    "spotipy>=2.24.0",
    "tqdm>=4.66.6",
    "yt-dlp>=2024.10.22",
]
